### ISSUE TITLE
Some clients have problem saving country for their system users

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#51] opened 2015-12-29 14:11 UTC
Some clients have problem saving country when they are creating or editing a system user.
This has been a problem several times before, probably because of bad connection with the database.

**Comment by mladjo2505** [comment] 2016-01-12 10:04
@hildegunn95 I would need some more information here, since it seems to be working correctly

**Comment by mladjo2505** [comment] 2016-03-13 12:28
Caused by integrity of DB migrations, some fields were not 100% migrated on some DBs.

**Comment by mladjo2505** [comment] 2016-04-12 06:23
We should make an integrity check script that is to be run after each migration.
The script should compare a structure of one good DB against all others and spit out the differences, if there are any. After that we can tailor migrations for specific DBs to fix the differences.

**Comment by mladjo2505** [comment] 2016-05-16 07:35
As we, @stoivo and I, talked we might want to create an additional table for migration.
Something of the following structure:

| MigrationID | MigrationName | Status |
| --- | --- | --- |
| 1 | example.sql | OK |

After adding this, each migration should have an insert query to this table at the beginning with status started and update status to ok at the end. That way we could check which migrations have been successfully run on each DB and possibly if there were some migrations that failed.

Maybe create a new issue for this(?)

**Comment by stoivo** [comment] 2016-05-16 07:52
Yes, go ahead.

**Comment by mladjo2505** [comment] 2016-05-16 08:15
Written up in #152 
Close this issue?

**Comment by stoivo** [comment] 2016-06-15 10:35
When we have completed #186 we can create a migration that will only contain a select with specific  columns like `select CountryID, Name, LandCode from countries`. If any of these fields does not exist the migration will fail with Column does not exist in table... This way we can find out which dbs that have wrongly structured tables.

Note: We can't check for things like indexes and if one table have more column than expected.

**Comment by mladjo2505** [comment] 2016-06-17 07:51
Maybe use the table `confdbfields` for the structure check, since it contains the structure of all tables in the current DB.

**Comment by hildegunn95** [comment] 2016-06-19 20:11
This is a file with some of the databases where I can't save countries for:
fb2014/Lodo/2016-06-19-cant_save_country_correctly.ods

**Comment by agvald** [comment] 2016-07-29 13:57
- [x] Scheme-checker needs to be implemented

**Comment by Baxxx** [comment] 2016-10-17 13:04
We need to create a perfectly migrated database which would be used only for checking structural integrity of other databases.

**Comment by mladjo2505** [comment] 2017-02-13 14:01
The original issue was dealt with by making custom migrations for databases and running them on the problematic dbs.
There is more to do with checking the consistency of all dbs but we will create a new issue on that.

**Closed as completed by mladjo2505** 2017-02-13 14:01 UTC
Labels: Waiting for more info
